include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - prefer_single_quotes
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - prefer_const_constructors_in_immutables
    - use_full_hex_values_for_flutter_colors
    - prefer_collection_literals
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_function_literals_in_foreach_calls
    - prefer_interpolation_to_compose_strings

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
